### ISSUE TITLE
A way to specify a different script than "start"

### ISSUE THREAD

**Issue by Ivanca** [apify/apify-cli#198]
I have 2 scrappers that share a lot of code so my scripts on package.json looks like this:
```
  "scripts": {
    "site1": "node build/scrape-site1.js",
    "site2": "node build/scrape-site2.js"
  },
```
but there is no way to tell the apify-cli wich one of the 2 I want to run, some way to specify what script I want to run such as `apify run site1 -p` would be great.

Thanks.

**Comment by Ivanca** [comment]
👋

**Comment by mnmkng** [comment]
Hi @Ivanca, there are currently no plans to support other script selection than `start`. `apify-cli` serves as a command line interface to the [Apify platform](https://apify.com) and [Actor](https://apify.com/actors) and the platform best practice is to parametrize actors using `INPUT` rather than `package.json` scripts. [You can read more about INPUT here](https://sdk.apify.com/docs/guides/getting-started#meet-the-input).

**Example for your case:**
`INPUT.json`
```json
{
    "site": 1
}
``` 
`main.js`
```js
const scrapeFirstSite = require(./build/scrape-site1);
const scrapeSecondSite = require(./build/scrape-site2);

// ...

const input = await Apify.getInput();
if (input.site === 1) {
    scrapeFirstSite();
} else {
    scrapeSecondSite();
}

// ...
```

It's a bit more work at first, but in the end it's much more customizable when you add more sites or need to pass multiple parameters, not only the site number.

Hope this helps!
