### ISSUE TITLE
Add 'blank' template to 'apify-create'

### ISSUE THREAD

**Issue by metalwarrior665** [apify/apify-cli#43]
When I want to start developing non-javascript Actor locally, I certainly don't need to any node_modules (or do I?) and possibly even apify_local storage.

It would be nice to have such a blank template that would still have the functionality like Apify push, apify  run etc.

**Comment by drobnikj** [comment]
For that use cases we created command `apify init` command, which creates apify.json and apify_local folder. You have to create your own Dockerfile and other stuff.

The problem is that you can not use `apify run` command in this case, because it counts with main.js as node app. But `apify push` and `apify call` work. There is one [example repo](https://github.com/drobnikj/apify-act-ruby).
