### ISSUE TITLE
Add option to quickly deploy the selected Actor template to Apify console

### ISSUE THREAD

**Issue by jbartadev** [apify/apify-cli#459]
We could improve the conversion between the CLI and Console by adding an additional option to the selected template prompt for `apify create` command.

## Current flow

`apify create`

1) **? Name of your new actor:**
2) **? Choose the programming language of your new actor: (Use arrow keys)**
3) **? Choose the programming language of your new actor: (Use arrow keys)
❯ JavaScript
  TypeScript
  Python**
  
 4) **❯ Start with JavaScript**
 5) **? Do you want to install the following template?
 Start with JavaScript:
 Scrape single page with provided URL with Axios and extract data from page's HT
ML with Cheerio. (Use arrow keys)
❯ Install template
  ──────────────
  Go back**
  
## My proposal

I'd add additional option to the step 5 - something like 

**❯ Install template
Deploy template to Apify Console
  ──────────────
  Go back****

The option would open the browser and either go to https://console.apify.com/actors/templates/js-start (the template detail) or it could create the Actor from the template straight away and go to the Actor detail page.

**Comment by jbartadev** [comment]
CC @HonzaTuron @fnesveda @B4nan

**Comment by B4nan** [comment]
We can surely add that, but I am not sure how it's gonna improve things. It feels weird to use CLI to open a webpage instead of installing the template locally, the path we should nurture here is pushing the local project I'd say. Maybe a hint at the end about using `apify push` would be more suitable? We could still do both for sure.

Sidenote: the code highlighting theme is apparently broken, looks like a dark theme pallete

<img width="577" alt="image" src="https://github.com/apify/apify-cli/assets/615580/e5809954-03be-400e-b5b5-1160e38b5bbe">

**Comment by jbartadev** [comment]
Let's add it as a message after the template installation, we'll ask for copy from marketing
